[tool.ruff]
# Enable certain rules
select = ["E", "F", "W", "I"]

# Exclude certain files or directories
exclude = [
    ".venv",
    ".git",
    "__pycache__",
    "docs",
    "build",
    "dist",
]

# Set the target Python version
target-version = "py310"

# Ignore certain error codes
ignore = [
]

# Set the maximum line length
max-line-length = 88

# Configure specific rules
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]  # Unused import
